from pathlib import Path
import re


def read(path):
    return Path(path).read_text()

def write(path, text):
    Path(path).write_text(text)

def rep(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected 1 occurrence, got {count}')
    return text.replace(old, new)

def sub(text, pattern, repl, label, flags=0):
    out, count = re.subn(pattern, repl, text, count=1, flags=flags)
    if count != 1:
        raise SystemExit(f'{label}: expected 1 substitution, got {count}')
    return out

# Setup: use the public term 学習者ID consistently.
p='src/components/SetupScreen.tsx'; t=read(p)
t=t.replace('先生から配られた4文字のコードを入力してね','先生から配られた4文字の学習者IDを入力してね')
t=t.replace('学習者用コードを確認できませんでした。先生に確認してください。','学習者IDを確認できませんでした。先生に確認してください。')
t=t.replace('4文字のコードを入力してね','4文字の学習者IDを入力してね')
t=t.replace('学習者用コード</span>','学習者ID</span>')
write(p,t)

# Dialogue header: always show the learner-entered ID.
p='src/components/Header.tsx'; t=read(p)
t=t.replace("Volume2, VolumeX, Clock, CheckCircle2, MessageCircle", "Volume2, VolumeX, Clock, CheckCircle2, MessageCircle, KeyRound")
t=rep(t,'  studentName: string;\n','  studentName: string;\n  learningId?: string;\n','header prop')
t=rep(t,'  studentName,\n','  studentName,\n  learningId,\n','header destructure')
needle='''        <div className="flex items-center gap-1.5 sm:gap-3 shrink-0">\n          <div className={`flex items-center gap-1.5 sm:gap-2 px-2.5 sm:px-3.5 py-2 sm:py-1.5 rounded-full border shadow-xs font-mono transition-all ${isTimeLow ? 'bg-rose-50 border-rose-300 text-rose-700 animate-pulse' : 'bg-white border-slate-200 text-slate-700'}`}>'''
repl='''        <div className="flex items-center gap-1.5 sm:gap-3 shrink-0">\n          {learningId && <div className="flex min-h-11 items-center gap-1.5 rounded-full border border-blue-200 bg-blue-50 px-2.5 text-[11px] font-black text-blue-800 sm:px-3"><KeyRound className="h-4 w-4" /><span className="hidden sm:inline">学習者ID</span><span className="tracking-widest">{learningId}</span></div>}\n          <div className={`flex items-center gap-1.5 sm:gap-2 px-2.5 sm:px-3.5 py-2 sm:py-1.5 rounded-full border shadow-xs font-mono transition-all ${isTimeLow ? 'bg-rose-50 border-rose-300 text-rose-700 animate-pulse' : 'bg-white border-slate-200 text-slate-700'}`}>'''
t=rep(t,needle,repl,'header learner id pill')
write(p,t)

# App passes the same learner ID to every learner-facing screen.
p='src/App.tsx'; t=read(p)
t=rep(t,'<Header studentName={profile.name} aiStudentName={currentAiStudent.name}', '<Header studentName={profile.name} learningId={learningCode} aiStudentName={currentAiStudent.name}', 'app header learning id')
t=rep(t,"{phase==='feedback'&&<FeedbackScreen profile={profile}", "{phase==='feedback'&&<FeedbackScreen profile={profile} learningId={learningCode}", 'app feedback learning id')
t=rep(t,"{phase==='history'&&<LearningHistoryScreen rows={historyRows}", "{phase==='history'&&<LearningHistoryScreen learningId={learningCode} rows={historyRows}", 'app history learning id')
write(p,t)

# Reflection title and public terminology.
p='src/components/ReflectionScreen.tsx'; t=read(p)
t=rep(t,'  const [submitted, setSubmitted] = useState(false);\n','  const [submitted, setSubmitted] = useState(false);\n  const reportOwner = profile.name && profile.name !== \'5・6年生\' ? profile.name : \'あなた\';\n','reflection report owner')
t=t.replace('学習者用コード ', '学習者ID ')
t=rep(t,"<h2 className=\"mt-2 text-2xl font-black text-slate-900\">{profile.name || '5・6年生'}さんの英会話レポート</h2>","<h2 className=\"mt-2 text-2xl font-black text-slate-900\">{reportOwner}の英会話レポート</h2>",'reflection report title')
t=t.replace("<div className=\"rounded-xl border border-slate-300 bg-white px-5 py-2 text-sm font-black\">お名前：{profile.name || '5・6年生'}</div>","{profile.name && profile.name !== '5・6年生' && <div className=\"rounded-xl border border-slate-300 bg-white px-5 py-2 text-sm font-black\">対話で話した名前：{profile.name}</div>}")
write(p,t)

# Feedback: title uses spoken name or あなた; show learner ID; place exchange-student message in the left column.
p='src/components/FeedbackScreen.tsx'; t=read(p)
t=t.replace("from '../data/vocabulary';","from '../data/vocabulary56';")
t=rep(t,'  profile: StudentProfile;\n','  profile: StudentProfile;\n  learningId?: string;\n','feedback prop')
t=rep(t,'  profile,\n  messages,','  profile,\n  learningId,\n  messages,','feedback destructure')
t=rep(t,'  const aiStudent = getAIStudentById(profile.selectedAiStudentId);\n','  const aiStudent = getAIStudentById(profile.selectedAiStudentId);\n  const reportOwner = profile.name && profile.name !== \'5・6年生\' ? profile.name : \'あなた\';\n','feedback report owner')
t=rep(t,"<h1 className=\"mt-1 text-xl font-black text-slate-900 sm:text-2xl\">{profile.name || '5・6年生'}さんの英会話レポート</h1>","<h1 className=\"mt-1 text-xl font-black text-slate-900 sm:text-2xl\">{reportOwner}の英会話レポート</h1>",'feedback title')
t=rep(t,'          <div className="flex flex-wrap items-center gap-2">\n            {onOpenHistory &&', '          <div className="flex flex-wrap items-center gap-2">\n            {learningId && <span className="rounded-xl border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-black text-blue-800">学習者ID <span className="tracking-widest">{learningId}</span></span>}\n            {onOpenHistory &&','feedback learner id')
message_block='''            <div className="mb-6 flex items-start gap-4 rounded-3xl border border-blue-200 bg-blue-50/80 p-5 shadow-sm sm:p-6">\n              <div className="h-14 w-14 shrink-0 overflow-hidden rounded-2xl border border-blue-300"><StudentAvatar student={aiStudent} size="sm" className="h-14 w-14" /></div>\n              <div><p className="mb-1 text-sm font-black text-blue-900">{aiStudent.name} からのメッセージ</p><p className="text-sm font-semibold leading-relaxed text-slate-800">“{feedback?.studentMessage || feedback?.overallComment || '話してくれてありがとう！また一緒に英語で話そうね。'}”</p></div>\n            </div>\n\n'''
t=rep(t,message_block,'','remove standalone student message')
next_section_end='''                </section>\n              </div>\n\n              <div className="flex flex-col gap-4 lg:col-span-5">'''
student_message_section='''                </section>\n                <section className="rounded-3xl border border-blue-200 bg-blue-50/80 p-5 shadow-sm sm:p-6">\n                  <div className="flex items-start gap-4"><div className="h-14 w-14 shrink-0 overflow-hidden rounded-2xl border border-blue-300"><StudentAvatar student={aiStudent} size="sm" className="h-14 w-14" /></div><div><h2 className="mb-1 text-sm font-black text-blue-900">{aiStudent.name} からのメッセージ</h2><p className="text-sm font-semibold leading-relaxed text-slate-800">“{feedback?.studentMessage || feedback?.overallComment || '話してくれてありがとう！また一緒に英語で話そうね。'}”</p></div></div>\n                </section>\n              </div>\n\n              <div className="flex flex-col gap-4 lg:col-span-5">'''
t=rep(t,next_section_end,student_message_section,'insert student message left')
write(p,t)

# Learning history: learner ID, new wording, and complete lists including zero counts.
p='src/components/LearningHistoryScreen.tsx'; t=read(p)
t=rep(t,'interface LearningHistoryScreenProps {\n','interface LearningHistoryScreenProps {\n  learningId?: string;\n','history prop')
t=rep(t,"export const LearningHistoryScreen: React.FC<LearningHistoryScreenProps> = ({ rows, loading, error, onBack }) => {", "export const LearningHistoryScreen: React.FC<LearningHistoryScreenProps> = ({ learningId, rows, loading, error, onBack }) => {", 'history destructure')
# Replace most-frequent memo blocks with complete count arrays.
t=sub(t,r"  const mostFrequentTopic = useMemo\(\(\) => \{.*?  \}, \[rows\]\);\n\n  const mostFrequentPartner = useMemo\(\(\) => \{.*?  \}, \[rows\]\);",'''  const topicCounts = useMemo(() => DIALOGUE_TOPICS.map((topic) => ({\n    id: topic.id, label: topic.title, count: rows.filter((row) => row.topic === topic.id).length,\n  })), [rows]);\n\n  const partnerCounts = useMemo(() => AI_STUDENTS_LIST.map((student) => ({\n    id: student.id, label: student.name, count: rows.filter((row) => row.aiStudentId === student.id).length,\n  })), [rows]);''','history counts',flags=re.S)
t=t.replace('これまでの自分の対話をふりかえります。ほかの人との比較はしません。','これまでのAI留学生との対話を振り返って，自分の学びに生かそう。')
old_header='''          <div className="mt-3 flex items-center gap-3"><BarChart3 className="h-8 w-8 text-blue-600" /><div><h1 className="text-xl font-black text-slate-900 sm:text-2xl">わたしの学習履歴</h1><p className="text-xs text-slate-600 sm:text-sm">これまでのAI留学生との対話を振り返って，自分の学びに生かそう。</p></div></div>'''
new_header='''          <div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><BarChart3 className="h-8 w-8 text-blue-600" /><div><h1 className="text-xl font-black text-slate-900 sm:text-2xl">わたしの学習履歴</h1><p className="text-xs text-slate-600 sm:text-sm">これまでのAI留学生との対話を振り返って，自分の学びに生かそう。</p></div></div>{learningId && <span className="rounded-xl border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-black text-blue-800">学習者ID <span className="tracking-widest">{learningId}</span></span>}</div>'''
t=rep(t,old_header,new_header,'history header learner id')
t=sub(t,r'''          <section className="grid gap-3 sm:grid-cols-2">\n            <div className="rounded-2xl border border-emerald-100 bg-emerald-50/70 p-4">.*?</div>\n            <div className="rounded-2xl border border-blue-100 bg-blue-50/70 p-4">.*?</div>\n          </section>''','''          <section className="grid gap-3 sm:grid-cols-2">\n            <div className="rounded-2xl border border-emerald-100 bg-emerald-50/70 p-4"><p className="text-[11px] font-bold text-emerald-800">よく話したテーマ</p><div className="mt-2 grid gap-1.5">{topicCounts.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border border-emerald-100 bg-white/80 px-3 py-2"><span className="text-xs font-bold text-slate-800">{item.label}</span><span className="text-xs font-black text-emerald-700">{item.count}回</span></div>)}</div></div>\n            <div className="rounded-2xl border border-blue-100 bg-blue-50/70 p-4"><p className="text-[11px] font-bold text-blue-800">よく話したAI留学生</p><div className="mt-2 grid gap-1.5">{partnerCounts.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border border-blue-100 bg-white/80 px-3 py-2"><span className="text-xs font-bold text-slate-800">{item.label}</span><span className="text-xs font-black text-blue-700">{item.count}回</span></div>)}</div></div>\n          </section>''','history full counts',flags=re.S)
write(p,t)

# Persistence: store/display the actual learner ID for teachers, keep research_id separate, add attendance number, and hide interrupted checkpoints from learner/teacher views.
p='src/server/persistence.ts'; t=read(p)
t=rep(t,"function normalizeClassId(value: unknown): string {\n  return typeof value === 'string' ? value.trim().slice(0, 40) : '';\n}\n", "function normalizeClassId(value: unknown): string {\n  return typeof value === 'string' ? value.trim().slice(0, 40) : '';\n}\nfunction normalizeAttendanceNumber(value: unknown): number | '' {\n  const parsed = Number(value);\n  return Number.isInteger(parsed) && parsed >= 1 && parsed <= 99 ? parsed : '';\n}\n", 'attendance helper')
t=sub(t,r"export async function resolveStudentByCode\(code: string\): Promise<\{ studentId: string; researchId: string; classId: string; active: boolean \} \| null> \{.*?\n\}",'''export async function resolveStudentByCode(code: string): Promise<{ studentId: string; researchId: string; classId: string; active: boolean; learningId: string; attendanceNumber: number | '' } | null> {\n  const learningId = code.trim().toUpperCase();\n  const key = learningCodeKey(learningId);\n  const doc = await getDocument(STUDENT_COLLECTION, key);\n  if (!doc || doc.active === false) return null;\n  const studentId = typeof doc.studentId === 'string' ? doc.studentId : '';\n  const researchId = typeof doc.researchId === 'string' ? doc.researchId : '';\n  if (!studentId || !researchId) return null;\n  if (String(doc.learningId || '') !== learningId) {\n    await setDocument(STUDENT_COLLECTION, key, { ...withoutInternal(doc), learningId, updatedAt: new Date().toISOString() });\n  }\n  return { studentId, researchId, classId: normalizeClassId(doc.classId), active: true, learningId, attendanceNumber: normalizeAttendanceNumber(doc.attendanceNumber) };\n}''','resolve student',flags=re.S)
t=sub(t,r"export async function createStudentCode\(\n  code: string,\n  studentId\?: string,\n  researchId\?: string,\n  classId\?: string,\n  teacherId\?: string\n\): Promise<\{ studentId: string; researchId: string; classId: string; teacherStudentId: string \}> \{",'''export async function createStudentCode(\n  code: string,\n  studentId?: string,\n  researchId?: string,\n  classId?: string,\n  teacherId?: string,\n  attendanceNumber?: unknown\n): Promise<{ studentId: string; researchId: string; classId: string; teacherStudentId: string; learningId: string; attendanceNumber: number | '' }> {''','create signature')
t=rep(t,"  const tid = validTeacherStudentId(teacherId) || await generateUniqueTeacherStudentId(sid);\n", "  const tid = validTeacherStudentId(teacherId);\n  const attendance = normalizeAttendanceNumber(attendanceNumber);\n", 'create no generated teacher id')
t=rep(t,"    teacherStudentId: tid,\n    classId: cid,\n", "    ...(tid ? { teacherStudentId: tid } : {}),\n    learningId: normalized,\n    attendanceNumber: attendance,\n    classId: cid,\n", 'create store learning id')
t=rep(t,"  return { studentId: sid, researchId: rid, classId: cid, teacherStudentId: tid };\n", "  return { studentId: sid, researchId: rid, classId: cid, teacherStudentId: tid, learningId: normalized, attendanceNumber: attendance };\n", 'create return')
# Replace management record function wholesale.
t=sub(t,r"export async function getStudentRecordsForManagement\(\): Promise<.*?\n\}\n\nexport async function setStudentActive",'''export async function getStudentRecordsForManagement(): Promise<Array<{ studentId: string; learningId: string; classId: string; attendanceNumber: number | ''; active: boolean; createdAt: string; updatedAt: string }>> {\n  const records = await listCollection(STUDENT_COLLECTION, 1000);\n  const grouped = new Map<string, Record<string, any>[]>();\n  for (const record of records) {\n    const sid = typeof record.studentId === 'string' ? record.studentId : '';\n    if (!sid) continue;\n    const list = grouped.get(sid) || []; list.push(record); grouped.set(sid, list);\n  }\n  const result: Array<{ studentId: string; learningId: string; classId: string; attendanceNumber: number | ''; active: boolean; createdAt: string; updatedAt: string }> = [];\n  for (const [studentId, list] of grouped.entries()) {\n    const sorted = list.slice().sort((a, b) => String(b.updatedAt || '').localeCompare(String(a.updatedAt || '')));\n    const activeRecord = sorted.find((row) => row.active !== false) || sorted[0] || {};\n    result.push({\n      studentId,\n      learningId: String(activeRecord.learningId || '').trim().toUpperCase(),\n      classId: normalizeClassId(activeRecord.classId),\n      attendanceNumber: normalizeAttendanceNumber(activeRecord.attendanceNumber),\n      active: sorted.some((row) => row.active !== false),\n      createdAt: String(activeRecord.createdAt || ''),\n      updatedAt: String(activeRecord.updatedAt || ''),\n    });\n  }\n  return result.sort((a, b) => a.classId.localeCompare(b.classId, 'ja') || (Number(a.attendanceNumber || 999) - Number(b.attendanceNumber || 999)) || a.learningId.localeCompare(b.learningId));\n}\n\nexport async function setStudentActive''','management records',flags=re.S)
# update class supports attendance number.
t=t.replace('export async function updateStudentClass(studentId: string, classId: string): Promise<void> {','export async function updateStudentClass(studentId: string, classId: string, attendanceNumber?: unknown): Promise<void> {')
t=sub(t,r"(export async function updateStudentClass\(studentId: string, classId: string, attendanceNumber\?: unknown\): Promise<void> \{\n  const cid = normalizeClassId\(classId\);\n  if \(!/\^\(\?:5-\[123\]\|6-\[123\]\|テスト\|予備\)\$/.test\(cid\)\) throw new Error\('INVALID_CLASS_ID'\);\n  const records = \(await listCollection\(STUDENT_COLLECTION, 1000\)\).filter\(\(row\) => row.studentId === studentId\);\n)", r"\1  const attendance = normalizeAttendanceNumber(attendanceNumber);\n", 'update class attendance local')
t=rep(t,"    await setDocument(STUDENT_COLLECTION, id, { ...withoutInternal(record), classId: cid, updatedAt: now });\n", "    await setDocument(STUDENT_COLLECTION, id, { ...withoutInternal(record), classId: cid, ...(attendance !== '' ? { attendanceNumber: attendance } : {}), updatedAt: now });\n", 'update class store attendance')
# reissue preserves same learner metadata and does not generate a new teacher-only ID.
t=t.replace("export async function reissueStudentCode(studentId: string, newCode: string): Promise<{ studentId: string; researchId: string; classId: string; teacherStudentId: string }> {", "export async function reissueStudentCode(studentId: string, newCode: string): Promise<{ studentId: string; researchId: string; classId: string; teacherStudentId: string; learningId: string; attendanceNumber: number | '' }> {")
t=rep(t,"  const tid = validTeacherStudentId(latest.teacherStudentId) || await generateUniqueTeacherStudentId(studentId, await listCollection(STUDENT_COLLECTION, 1000));\n  const created = await createStudentCode(newCode, studentId, String(latest.researchId || ''), normalizeClassId(latest.classId), tid);\n", "  const tid = validTeacherStudentId(latest.teacherStudentId);\n  const created = await createStudentCode(newCode, studentId, String(latest.researchId || ''), normalizeClassId(latest.classId), tid, latest.attendanceNumber);\n", 'reissue metadata')
# completed learner/teacher sessions only.
marker='''export async function getStudentHistory(studentId: string): Promise<Record<string, unknown>[]> {\n  const rows = await queryCollection(SESSION_COLLECTION, 'studentId', studentId, 5000);\n  return rows.sort'''
replacement='''function learnerTeacherVisibleSession(session: Record<string, any>): boolean {\n  const events = Array.isArray(session.systemEvents) ? session.systemEvents : [];\n  const hasFinish = events.some((event: any) => event?.type === 'session_finish');\n  const hasReflection = Boolean(session.reflection && typeof session.reflection === 'object');\n  const schemaVersion = Number(session.schemaVersion || 0);\n  const turns = Number(session.totalTurns || 0);\n  return hasFinish || hasReflection || (schemaVersion < 3 && turns > 0);\n}\n\nexport async function getStudentHistory(studentId: string): Promise<Record<string, unknown>[]> {\n  const rows = (await queryCollection(SESSION_COLLECTION, 'studentId', studentId, 5000)).filter(learnerTeacherVisibleSession);\n  return rows.sort'''
t=rep(t,marker,replacement,'learner visible filter')
# teacher sessions join learnerId and attendance, not research/teacher opaque ID.
t=sub(t,r"export async function getTeacherSessionsForManagement\(\): Promise<Record<string, any>\[]> \{.*?\n\}",'''export async function getTeacherSessionsForManagement(): Promise<Record<string, any>[]> {\n  const [rows, students] = await Promise.all([getAllSessionsForManagement(), getStudentRecordsForManagement()]);\n  const records = new Map(students.map((student) => [student.studentId, student]));\n  return rows.filter(learnerTeacherVisibleSession).map(({ researchId: _researchId, _name, ...session }) => {\n    const rec = records.get(String(session.studentId || ''));\n    return {\n      ...session,\n      classId: normalizeClassId(session.classId || rec?.classId || ''),\n      learningId: rec?.learningId || '',\n      attendanceNumber: rec?.attendanceNumber ?? '',\n    };\n  });\n}''','teacher session join',flags=re.S)
write(p,t)

# Server teacher code management supports learner ID + attendance number and stops returning opaque teacher IDs.
p='server.ts'; t=read(p)
t=rep(t,"if(action==='create'){const code=normalizeLearningCode(req.body?.learningCode);const classId=typeof req.body?.classId==='string'?req.body.classId.trim():'';if(!isValidLearningCode(req.body?.learningCode))return res.status(400).json({success:false,error:'INVALID_LEARNING_CODE'});if(!/^(?:5-[123]|6-[123]|テスト|予備)$/.test(classId))return res.status(400).json({success:false,error:'CLASS_ID_REQUIRED'});const created=await createStudentCode(code,undefined,undefined,classId);return res.json({success:true,studentId:created.studentId,teacherStudentId:created.teacherStudentId,classId:created.classId});}","if(action==='create'){const code=normalizeLearningCode(req.body?.learningCode);const classId=typeof req.body?.classId==='string'?req.body.classId.trim():'';const attendanceNumber=Number(req.body?.attendanceNumber);if(!isValidLearningCode(req.body?.learningCode))return res.status(400).json({success:false,error:'INVALID_LEARNING_CODE'});if(!/^(?:5-[123]|6-[123]|テスト|予備)$/.test(classId))return res.status(400).json({success:false,error:'CLASS_ID_REQUIRED'});if(!Number.isInteger(attendanceNumber)||attendanceNumber<1||attendanceNumber>99)return res.status(400).json({success:false,error:'ATTENDANCE_NUMBER_REQUIRED'});const created=await createStudentCode(code,undefined,undefined,classId,undefined,attendanceNumber);return res.json({success:true,studentId:created.studentId,learningId:created.learningId,classId:created.classId,attendanceNumber:created.attendanceNumber});}",'server create learner id')
t=rep(t,"if(action==='reissue'){const studentId=typeof req.body?.studentId==='string'?req.body.studentId:'';if(!studentId||!isValidLearningCode(req.body?.learningCode))return res.status(400).json({success:false,error:'INVALID_REISSUE_REQUEST'});const created=await reissueStudentCode(studentId,normalizeLearningCode(req.body.learningCode));return res.json({success:true,studentId:created.studentId,teacherStudentId:created.teacherStudentId,classId:created.classId});}","if(action==='reissue'){const studentId=typeof req.body?.studentId==='string'?req.body.studentId:'';if(!studentId||!isValidLearningCode(req.body?.learningCode))return res.status(400).json({success:false,error:'INVALID_REISSUE_REQUEST'});const created=await reissueStudentCode(studentId,normalizeLearningCode(req.body.learningCode));return res.json({success:true,studentId:created.studentId,learningId:created.learningId,classId:created.classId,attendanceNumber:created.attendanceNumber});}",'server reissue')
t=rep(t,"if(action==='update-class'){const studentId=typeof req.body?.studentId==='string'?req.body.studentId:'';const classId=typeof req.body?.classId==='string'?req.body.classId.trim():'';if(!studentId||!/^(?:5-[123]|6-[123]|テスト|予備)$/.test(classId))return res.status(400).json({success:false,error:'INVALID_CLASS_UPDATE'});await updateStudentClass(studentId,classId);return res.json({success:true,classId});}","if(action==='update-class'){const studentId=typeof req.body?.studentId==='string'?req.body.studentId:'';const classId=typeof req.body?.classId==='string'?req.body.classId.trim():'';const attendanceNumber=req.body?.attendanceNumber; if(!studentId||!/^(?:5-[123]|6-[123]|テスト|予備)$/.test(classId))return res.status(400).json({success:false,error:'INVALID_CLASS_UPDATE'});await updateStudentClass(studentId,classId,attendanceNumber);return res.json({success:true,classId,attendanceNumber});}",'server update class')
write(p,t)

# Research quality: reflection is evidence the dialogue reached the reflection stage even if old event logs lack session_finish.
p='src/server/researchExport.ts'; t=read(p)
t=rep(t,"    const legacyCompletionEvidence = Boolean(session.endedAt) && hasReflection && (systemEvents.length === 0 || schemaVersion < 3);\n    const dialogueCompleted = hasSessionFinish || legacyCompletionEvidence;\n", "    const reflectionCompletionEvidence = Boolean(session.endedAt) && hasReflection;\n    const legacyCompletionEvidence = Boolean(session.endedAt) && schemaVersion < 3 && childMessages.length > 0;\n    const dialogueCompleted = hasSessionFinish || reflectionCompletionEvidence || legacyCompletionEvidence;\n", 'research legacy completion')
write(p,t)

# Management page: actual learner IDs for teacher views, live filters, clearer refresh, consistent all-scope charts and weekly labels.
p='src/server/managementPage.ts'; t=read(p)
t=t.replace('児童ID管理','学習者ID管理')
t=t.replace('児童ID','学習者ID')
t=t.replace('<button id="refreshBtn" class="secondary">更新</button>','<span id="lastUpdated" class="muted"></span><button id="refreshBtn" class="secondary">↻ 最新データを再読込</button>')
# Remove duplicate lower research shortcuts (top navigation remains).
t=re.sub(r'<div class="cards3" style="margin-top:12px"><button id="researchExportShortcut".*?</div></div>\n</section>', '</div></div>\n</section>', t, count=1)
# T6 form and columns.
t=t.replace('<label>新しい4文字コード</label><input id="newCode" maxlength="4" placeholder="例 A7M4">','<label>新しい学習者ID</label><input id="newCode" maxlength="4" placeholder="例 A7M4">')
t=t.replace('<div><label>学級</label><select id="newClass"></select></div><div style="display:flex;align-items:end"><button id="issueCodeBtn"', '<div><label>学級</label><select id="newClass"></select></div><div><label>出席番号</label><input id="newAttendance" type="number" min="1" max="99" placeholder="例 12"></div><div style="display:flex;align-items:end"><button id="issueCodeBtn"')
t=t.replace('<th>学習者ID</th><th>学級</th><th>利用状態</th>','<th>学習者ID</th><th>学級</th><th>出席番号</th><th>利用状態</th>')
# Rename search placeholder if present.
t=t.replace('placeholder="児童IDで検索"','placeholder="学習者IDで検索"')
# Weekly axis label: show weekly range rather than a misleading single date.
t=rep(t,"function axisLabel(k){return k.length===7?k.replace('-', '/'):k.slice(5).replace('-', '/')}\n", "function axisLabel(k){if(k.indexOf('~')>0){var p=k.split('~');return p[0].slice(5).replace('-', '/')+'〜'+p[1].slice(5).replace('-', '/')}return k.length===7?k.replace('-', '/'):k.slice(5).replace('-', '/')}\n", 'axis weekly label') if "function axisLabel(k){return k.length===7?k.replace('-', '/'):k.slice(5).replace('-', '/')}\n" in t else t
# periodKey weekly returns Monday~Sunday while preserving lexical ordering.
old="function periodKey(d,mode){if(!d)return'';if(mode==='day')return d;if(mode==='month')return d.slice(0,7);var dt=new Date(d+'T00:00:00Z');var day=(dt.getUTCDay()+6)%7;dt.setUTCDate(dt.getUTCDate()-day);return dt.toISOString().slice(0,10)}"
new="function periodKey(d,mode){if(!d)return'';if(mode==='day')return d;if(mode==='month')return d.slice(0,7);var dt=new Date(d+'T00:00:00Z');var day=(dt.getUTCDay()+6)%7;dt.setUTCDate(dt.getUTCDate()-day);var start=dt.toISOString().slice(0,10);dt.setUTCDate(dt.getUTCDate()+6);return start+'~'+dt.toISOString().slice(0,10)}"
t=rep(t,old,new,'period weekly range')
# teacher all scope is one all-data series, not 学級未設定.
t=rep(t,"var classes=c==='all'?scopeClasses('all',rows):scopeClasses(c,rows),metric=$('teacherMetric').value", "var classes=c==='all'?(rows.length?['すべて']:[]):scopeClasses(c,rows),metric=$('teacherMetric').value", 'teacher all series')
# Teacher support: show learning ID and class/number, not opaque teacher ID.
t=sub(t,r"function teacherSupportHtml\(recs,rows\)\{.*?\}\nfunction teacherReflectionHtml",'''function teacherSupportHtml(recs,rows){var by={};rows.forEach(function(r){(by[r.studentId]||(by[r.studentId]=[])).push(r)});var items=recs.map(function(rec){var rs=by[rec.studentId]||[],last=rs.map(dateOf).sort().pop()||'—';return{rec:rec,count:rs.length,last:last}}).sort(function(a,b){return a.count-b.count||a.last.localeCompare(b.last)}).slice(0,5);if(!items.length)return '<div class="empty-note">対象児童がいません</div>';return '<table class="support-table"><thead><tr><th>学習者ID</th><th>学級・番号</th><th>実施</th><th>最終</th><th>確認</th></tr></thead><tbody>'+items.map(function(x){var label=(x.rec.classId||'未設定')+(x.rec.attendanceNumber?(' '+x.rec.attendanceNumber+'番'):'');return '<tr><td>'+esc(x.rec.learningId||'未登録')+'</td><td>'+esc(label)+'</td><td>'+x.count+'回</td><td>'+esc(x.last)+'</td><td><span class="support-tag">'+(x.count===0?'未実施':x.count===1?'1回のみ':'継続中')+'</span></td></tr>'}).join('')+'</tbody></table>'}\nfunction teacherReflectionHtml''','teacher support ids',flags=re.S)
# Teacher list/open uses studentId internally but displays learningId.
t=sub(t,r"function teacherStudentRows\(\)\{.*?\}\nfunction studentAllRows\(\)\{.*?\}\nfunction setSummaryQuick",'''function teacherStudentRows(){var c=$('listClass').value,s=$('listStart').value,e=$('listEnd').value,q=$('studentSearch').value.trim().toUpperCase(),showUnused=$('showUnused').checked;var out=[];studentRecords.forEach(function(rec){if(!classMatches(rec.classId,c))return;if(q&&String(rec.learningId||'').toUpperCase().indexOf(q)<0)return;var rows=teacherSessions.filter(function(x){return x.studentId===rec.studentId&&within(x,s,e)}).sort(function(a,b){return dateOf(a).localeCompare(dateOf(b))});if(!rows.length&&!showUnused)return;out.push({rec:rec,rows:rows})});$('studentRows').innerHTML=out.map(function(x){var rows=x.rows,lastRow=rows[rows.length-1],last=lastRow?dateOf(lastRow):'—',totalDuration=rows.reduce(function(a,r){return a+n(r.actualDurationSeconds)},0),classNo=(x.rec.classId||'未設定')+(x.rec.attendanceNumber?(' '+x.rec.attendanceNumber+'番'):'');return '<tr><td><button class="link student-open" data-id="'+esc(x.rec.studentId)+'">'+esc(x.rec.learningId||'未登録')+'</button></td><td>'+esc(classNo)+'</td><td>'+rows.length+'回</td><td>'+secText(totalDuration)+'</td><td>'+secText(avg(rows.map(function(r){return r.actualDurationSeconds})))+'</td><td>'+avg(rows.map(function(r){return r.totalTurns})).toFixed(1)+'</td><td>'+avg(rows.map(function(r){return r.totalChildWords})).toFixed(1)+'</td><td>'+esc(lastRow?topicText(lastRow.topic):'—')+'</td><td>'+esc(last)+'</td><td><span class="status '+(x.rec.active?'':'off')+'">'+(rows.length?(x.rec.active?'利用中':'利用停止'):'未実施')+'</span></td></tr>'}).join('');document.querySelectorAll('.student-open').forEach(function(b){b.addEventListener('click',function(){openStudent(b.dataset.id)})})}\nfunction studentAllRows(){var rec=studentRecords.find(function(r){return r.studentId===currentTeacherStudent});if(!rec)return[];return teacherSessions.filter(function(r){return r.studentId===rec.studentId}).sort(function(a,b){return dateOf(a).localeCompare(dateOf(b))})}\nfunction setSummaryQuick''','teacher list ids',flags=re.S)
t=sub(t,r"function openStudent\(tid\)\{currentTeacherStudent=tid;var rec=studentRecords.find\(function\(r\)\{return r.teacherStudentId===tid\}\);if\(!rec\)return;setText\('summaryCrumb',tid\);setText\('studentSummaryTitle',tid\+'の学習状況'\);show\('studentSummary'\);setSummaryQuick\('all'\)\}","function openStudent(studentId){currentTeacherStudent=studentId;var rec=studentRecords.find(function(r){return r.studentId===studentId});if(!rec)return;var label=rec.learningId||'未登録';setText('summaryCrumb',label);setText('studentSummaryTitle',label+'の学習状況');show('studentSummary');setSummaryQuick('all')}",'open student')
# renderCodes is updated by a separate focused patch.
# Create-code handler includes attendance and displays learner ID.
issue_handler = "$('issueCodeBtn').addEventListener('click',async function(){var code=$('newCode').value.trim().toUpperCase(),cls=$('newClass').value,no=Number($('newAttendance').value);if(!/^[A-Z0-9]{4}$/.test(code)){setText('codeMessage','英数字4文字の学習者IDを入力してください。');return}if(!cls){setText('codeMessage','学級を選択してください。');return}if(!Number.isInteger(no)||no<1||no>99){setText('codeMessage','出席番号を入力してください。');return}try{var d=await mutateCode({action:'create',learningCode:code,classId:cls,attendanceNumber:no});setText('codeMessage','発行しました。学習者ID: '+d.learningId);$('newCode').value='';$('newAttendance').value='';await loadTeacher()}catch(e){setText('codeMessage',String(e.message||e))}});"
issue_start=t.index("$('issueCodeBtn').addEventListener")
issue_end=t.index("$('reissueCancel').addEventListener", issue_start)
t=t[:issue_start]+issue_handler+t[issue_end:]
# Refresh retains filters and reports actual reload time.
t=rep(t,"$('refreshBtn').addEventListener('click',function(){role==='teacher'?loadTeacher():loadResearch()});", "$('refreshBtn').addEventListener('click',async function(){var b=this,old=b.textContent;b.disabled=true;b.textContent='読込中…';try{if(role==='teacher')await loadTeacher();else await loadResearch();setText('lastUpdated','最終更新 '+new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit'}))}finally{b.disabled=false;b.textContent=old}});", 'refresh behavior')
# Remove explicit reset of research scope to all during reload.
t=t.replace("fillResearchScopeSelect('researchDashboardClass');$('researchDashboardClass').value='all';","fillResearchScopeSelect('researchDashboardClass');")
# Dates react immediately on input as well as change; selects remain change.
t=rep(t,"['teacherClass','teacherStart','teacherEnd','teacherMetric'].forEach(function(id){$(id).addEventListener('change',updateTeacherDashboard)});", "['teacherClass','teacherMetric'].forEach(function(id){$(id).addEventListener('change',updateTeacherDashboard)});['teacherStart','teacherEnd'].forEach(function(id){$(id).addEventListener('input',updateTeacherDashboard);$(id).addEventListener('change',updateTeacherDashboard)});", 'teacher live dates')
t=rep(t,"['researchStart','researchEnd','researchDashboardClass','researchMetric'].forEach(function(id){$(id).addEventListener('change',updateResearchDashboard)});", "['researchDashboardClass','researchMetric'].forEach(function(id){$(id).addEventListener('change',updateResearchDashboard)});['researchStart','researchEnd'].forEach(function(id){$(id).addEventListener('input',updateResearchDashboard);$(id).addEventListener('change',updateResearchDashboard)});", 'research live dates')
# research condition text distinguishes selected range from actual data range.
t=rep(t,"setText('researchConditionSummary','収集期間: '+(ds.length?ds[0]+'〜'+ds[ds.length-1]:'—')+' ／ 対象: '", "setText('researchConditionSummary','選択期間: '+(s||'—')+'〜'+(e||'—')+' ／ 実データ: '+(ds.length?ds[0]+'〜'+ds[ds.length-1]:'—')+' ／ 対象: '", 'research period summary')
write(p,t)

# Add focused identity/filter QA and include it in npm qa.
p='scripts/qa-learner-identity-sync.ts'; write(p,'''import assert from 'node:assert/strict';\nimport fs from 'node:fs';\nimport { managementPageHtml } from '../src/server/managementPage';\n\nconst setup = fs.readFileSync('src/components/SetupScreen.tsx','utf8');\nconst header = fs.readFileSync('src/components/Header.tsx','utf8');\nconst reflection = fs.readFileSync('src/components/ReflectionScreen.tsx','utf8');\nconst feedback = fs.readFileSync('src/components/FeedbackScreen.tsx','utf8');\nconst history = fs.readFileSync('src/components/LearningHistoryScreen.tsx','utf8');\nconst persistence = fs.readFileSync('src/server/persistence.ts','utf8');\nconst server = fs.readFileSync('server.ts','utf8');\nconst management = managementPageHtml();\n\nassert.ok(setup.includes('学習者ID'));\nassert.ok(!setup.includes('学習者用コード</span>'));\nassert.ok(header.includes('learningId?: string') && header.includes('学習者ID'));\nassert.ok(reflection.includes("reportOwner") && reflection.includes('学習者ID'));\nassert.ok(feedback.includes("reportOwner") && feedback.includes('learningId?: string'));\nassert.ok(history.includes('これまでのAI留学生との対話を振り返って，自分の学びに生かそう。'));\nassert.ok(history.includes('topicCounts.map') && history.includes('partnerCounts.map'));\nassert.ok(persistence.includes('learningId: normalized'));\nassert.ok(persistence.includes('attendanceNumber'));\nassert.ok(persistence.includes('rows.filter(learnerTeacherVisibleSession)'));\nassert.ok(server.includes('attendanceNumber'));\nassert.ok(management.includes('↻ 最新データを再読込'));\nassert.ok(management.includes('学習者ID'));\nassert.ok(!management.includes('児童ID管理'));\nassert.ok(management.includes("rows.length?['すべて']:[]"));\nassert.ok(management.includes("addEventListener('input',updateResearchDashboard)"));\nassert.ok(management.includes("addEventListener('input',updateTeacherDashboard)"));\nassert.ok(!management.includes('researchListShortcut'), 'duplicate lower research navigation should be removed');\nconsole.log('Learner identity and dashboard synchronization QA: PASS');\n''')

p='package.json'; t=read(p)
t=rep(t,'"qa:dashboard": "tsx scripts/qa-dashboard-data-sync.ts"','"qa:dashboard": "tsx scripts/qa-dashboard-data-sync.ts",\n    "qa:identity": "tsx scripts/qa-learner-identity-sync.ts"','package identity script')
t=rep(t,'npm run qa:research && npm run qa:dashboard && npm run lint','npm run qa:research && npm run qa:dashboard && npm run qa:identity && npm run lint','package qa chain')
write(p,t)

print('Learner ID / dashboard patch applied')
