from pathlib import Path

p=Path('src/server/managementPage.ts')
s=p.read_text()

old="var $=function(id){return document.getElementById(id)};var role='';var teacherSessions=[];var studentRecords=[];var researchData=[];var currentTeacherStudent='';var currentResearchId='';var currentResearchSession='';var teacherAgg='day';var researchAgg='day';var exportHistory=[];"
new="var $=function(id){return document.getElementById(id)};var role='';var teacherSessions=[];var studentRecords=[];var researchData=[];var currentTeacherStudent='';var currentResearchId='';var currentResearchSession='';var teacherAgg='day';var researchAgg='day';var exportHistory=[];function captureControlState(ids){var state={};ids.forEach(function(id){var e=$(id);if(!e)return;state[id]=e.type==='checkbox'?e.checked:e.value});return state}function restoreControlState(state){Object.keys(state||{}).forEach(function(id){var e=$(id);if(!e)return;if(e.type==='checkbox'){e.checked=Boolean(state[id]);return}if(e.tagName==='SELECT'&&!Array.from(e.options||[]).some(function(o){return o.value===state[id]}))return;e.value=state[id]})}function markDataUpdated(){setText('lastUpdated','最終更新 '+new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit'}))}"
if old not in s: raise SystemExit('state anchor not found')
s=s.replace(old,new,1)

old="async function loadTeacher(){var a=await Promise.all([fetch('/api/management/sessions'),fetch('/api/management/student-codes')]),sd=await a[0].json(),cd=await a[1].json();if(!a[0].ok||!sd.success)throw new Error(sd.error||'DATA_ERROR');if(!a[1].ok||!cd.success)throw new Error(cd.error||'CODE_ERROR');studentRecords=(Array.isArray(cd.students)?cd.students:[]).map(function(rec){rec.classId=canonClass(rec.classId||'');return rec});var classByStudent={};studentRecords.forEach(function(rec){classByStudent[rec.studentId]=rec.classId});teacherSessions=(Array.isArray(sd.sessions)?sd.sessions:[]).map(function(row){row.classId=canonClass(row.classId||classByStudent[row.studentId]||'');return row});fillSchoolClassSelect('teacherClass','すべて');fillSchoolClassSelect('listClass','すべて');fillSchoolClassSelect('newClass','');initDates('teacher',teacherSessions);initDates('list',teacherSessions);$('listStart').value=$('teacherStart').value;$('listEnd').value=$('teacherEnd').value;updateTeacherDashboard();teacherStudentRows();renderCodes()}"
new="async function loadTeacher(options){var preserve=Boolean(options&&options.preserveFilters),state=preserve?captureControlState(['teacherClass','teacherStart','teacherEnd','teacherMetric','listClass','listStart','listEnd','studentSearch','showUnused','summaryStart','summaryEnd','newClass']):null;var a=await Promise.all([fetch('/api/management/sessions'),fetch('/api/management/student-codes')]),sd=await a[0].json(),cd=await a[1].json();if(!a[0].ok||!sd.success)throw new Error(sd.error||'DATA_ERROR');if(!a[1].ok||!cd.success)throw new Error(cd.error||'CODE_ERROR');studentRecords=(Array.isArray(cd.students)?cd.students:[]).map(function(rec){rec.classId=canonClass(rec.classId||'');return rec});var classByStudent={};studentRecords.forEach(function(rec){classByStudent[rec.studentId]=rec.classId});teacherSessions=(Array.isArray(sd.sessions)?sd.sessions:[]).map(function(row){row.classId=canonClass(row.classId||classByStudent[row.studentId]||'');return row});fillSchoolClassSelect('teacherClass','すべて');fillSchoolClassSelect('listClass','すべて');fillSchoolClassSelect('newClass','');initDates('teacher',teacherSessions);initDates('list',teacherSessions);if(preserve){restoreControlState(state)}else{$('listStart').value=$('teacherStart').value;$('listEnd').value=$('teacherEnd').value}updateTeacherDashboard();teacherStudentRows();renderCodes();if(currentTeacherStudent)updateStudentSummary();markDataUpdated()}"
if old not in s: raise SystemExit('loadTeacher anchor not found')
s=s.replace(old,new,1)

old="async function loadResearch(){var r=await fetch('/api/management/research.csv');if(!r.ok)throw new Error('RESEARCH_DATA_UNAVAILABLE');researchData=csvParse(await r.text());fillResearchScopeSelect('researchDashboardClass');fillSchoolClassSelect('researchClass','すべて');fillSchoolClassSelect('r6Class','すべて');initDates('research',researchData);initDates('r3',researchData);initDates('r6',researchData);$('r3Start').value=$('researchStart').value;$('r3End').value=$('researchEnd').value;$('r6Start').value=$('researchStart').value;$('r6End').value=$('researchEnd').value;var ids=Array.from(new Set(researchData.map(function(x){return x.research_id}).filter(Boolean))).sort();fillSelect('r6Research',ids,'すべて');updateResearchDashboard();renderResearchList();renderQuality()}"
new="async function loadResearch(options){var preserve=Boolean(options&&options.preserveFilters),state=preserve?captureControlState(['researchStart','researchEnd','researchDashboardClass','researchMetric','r3Start','r3End','researchClass','researchGrade','researchCompleteOnly','researchSearch','r4Start','r4End','r6Start','r6End','r6Class','r6Research','r6CompleteOnly']):null;var r=await fetch('/api/management/research.csv');if(!r.ok)throw new Error('RESEARCH_DATA_UNAVAILABLE');researchData=csvParse(await r.text());fillResearchScopeSelect('researchDashboardClass');fillSchoolClassSelect('researchClass','すべて');fillSchoolClassSelect('r6Class','すべて');initDates('research',researchData);initDates('r3',researchData);initDates('r6',researchData);var ids=Array.from(new Set(researchData.map(function(x){return x.research_id}).filter(Boolean))).sort();fillSelect('r6Research',ids,'すべて');if(preserve){restoreControlState(state)}else{$('r3Start').value=$('researchStart').value;$('r3End').value=$('researchEnd').value;$('r6Start').value=$('researchStart').value;$('r6End').value=$('researchEnd').value}updateResearchDashboard();renderResearchList();renderQuality();if(currentResearchId)updateResearchSummary();markDataUpdated()}"
if old not in s: raise SystemExit('loadResearch anchor not found')
s=s.replace(old,new,1)

old="$('loginTeacherTab').addEventListener('click',function(){$('loginTeacherTab').classList.add('active');$('loginResearchTab').classList.remove('active');setText('loginHint','授業運営と児童支援のための教師管理画面です')});$('loginResearchTab').addEventListener('click',function(){$('loginResearchTab').classList.add('active');$('loginTeacherTab').classList.remove('active');setText('loginHint','匿名化された縦断分析とデータ品質のための研究者画面です')});$('loginBtn').addEventListener('click',doLogin);$('logoutBtn').addEventListener('click',async function(){await fetch('/api/management/logout',{method:'POST'});location.reload()});$('refreshBtn').addEventListener('click',async function(){var b=this,old=b.textContent;b.disabled=true;b.textContent='読込中…';try{if(role==='teacher')await loadTeacher();else await loadResearch();setText('lastUpdated','最終更新 '+new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit'}))}finally{b.disabled=false;b.textContent=old}});"
new="$('loginTeacherTab').addEventListener('click',function(){$('loginTeacherTab').classList.add('active');$('loginResearchTab').classList.remove('active');setText('loginHint','授業運営と児童支援のための教師管理画面です')});$('loginResearchTab').addEventListener('click',function(){$('loginResearchTab').classList.add('active');$('loginTeacherTab').classList.remove('active');setText('loginHint','匿名化された縦断分析とデータ品質のための研究者画面です')});$('loginBtn').addEventListener('click',doLogin);$('logoutBtn').addEventListener('click',async function(){await fetch('/api/management/logout',{method:'POST'});location.reload()});$('refreshBtn').addEventListener('click',async function(){var b=this,old=b.textContent;b.disabled=true;b.textContent='読込中…';try{if(role==='teacher')await loadTeacher({preserveFilters:true});else await loadResearch({preserveFilters:true})}catch(e){alert(String(e.message||e))}finally{b.disabled=false;b.textContent=old}});"
if old not in s: raise SystemExit('refresh anchor not found')
s=s.replace(old,new,1)

old="['listClass','listStart','listEnd','studentSearch','showUnused'].forEach(function(id){$(id).addEventListener(id==='studentSearch'?'input':'change',teacherStudentRows)});['summaryStart','summaryEnd'].forEach(function(id){$(id).addEventListener('change',updateStudentSummary)});"
new="['listClass','showUnused'].forEach(function(id){$(id).addEventListener('change',teacherStudentRows)});$('studentSearch').addEventListener('input',teacherStudentRows);['listStart','listEnd'].forEach(function(id){$(id).addEventListener('input',teacherStudentRows);$(id).addEventListener('change',teacherStudentRows)});['summaryStart','summaryEnd'].forEach(function(id){$(id).addEventListener('input',updateStudentSummary);$(id).addEventListener('change',updateStudentSummary)});"
if old not in s: raise SystemExit('teacher filter anchor not found')
s=s.replace(old,new,1)

old="['r3Start','r3End','researchClass','researchGrade','researchCompleteOnly'].forEach(function(id){$(id).addEventListener('change',renderResearchList)});$('researchSearch').addEventListener('input',renderResearchList);['r4Start','r4End'].forEach(function(id){$(id).addEventListener('change',updateResearchSummary)});['r6Start','r6End','r6Class','r6Research','r6CompleteOnly'].forEach(function(id){$(id).addEventListener('change',renderQuality)});"
new="['researchClass','researchGrade','researchCompleteOnly'].forEach(function(id){$(id).addEventListener('change',renderResearchList)});['r3Start','r3End'].forEach(function(id){$(id).addEventListener('input',renderResearchList);$(id).addEventListener('change',renderResearchList)});$('researchSearch').addEventListener('input',renderResearchList);['r4Start','r4End'].forEach(function(id){$(id).addEventListener('input',updateResearchSummary);$(id).addEventListener('change',updateResearchSummary)});['r6Class','r6Research','r6CompleteOnly'].forEach(function(id){$(id).addEventListener('change',renderQuality)});['r6Start','r6End'].forEach(function(id){$(id).addEventListener('input',renderQuality);$(id).addEventListener('change',renderQuality)});"
if old not in s: raise SystemExit('research filter anchor not found')
s=s.replace(old,new,1)

p.write_text(s)

q=Path('scripts/qa-learner-identity-sync.ts')
t=q.read_text()
anchor="assert.ok(management.includes('↻ 最新データを再読込'));\n"
extra="""assert.ok(management.includes('↻ 最新データを再読込'));
assert.ok(management.includes('captureControlState') && management.includes('restoreControlState'), 'reload must preserve current filter conditions');
assert.ok(management.includes("loadTeacher({preserveFilters:true})") && management.includes("loadResearch({preserveFilters:true})"), 'reload button must fetch fresh data without resetting filters');
assert.ok(management.includes("function markDataUpdated()") && management.includes("最終更新 "), 'last Firestore reload time must be displayed');
assert.ok(management.includes("['listStart','listEnd'].forEach(function(id){$(id).addEventListener('input',teacherStudentRows)"), 'teacher date filters must render immediately');
assert.ok(management.includes("['r3Start','r3End'].forEach(function(id){$(id).addEventListener('input',renderResearchList)"), 'research date filters must render immediately');
"""
if anchor not in t: raise SystemExit('QA anchor not found')
t=t.replace(anchor,extra,1)
q.write_text(t)
print('management refresh semantics applied')
