from pathlib import Path
import re
p=Path('src/server/managementPage.ts')
s=p.read_text()
s=s.replace('<p class="warn">学級情報は今後の新規コード発行時から紐付けます。既存データは「未設定」として扱います。</p>','<p class="note">学級は学習者用コード発行時に設定し、以後のセッションへ自動で引き継がれます。</p>')
s=s.replace('<select><option>すべての学級</option></select>','<select id="researchClass"><option value="all">すべての学級</option><option value="5-1">5年1組</option><option value="5-2">5年2組</option><option value="6-1">6年1組</option></select>',1)
s=s.replace("let currentUser=null,teacherSessions=[],researchRows=[],selectedStudent='';","let currentUser=null,teacherSessions=[],teacherRecords=[],researchRows=[],selectedStudent='';")
s=s.replace("async function loadTeacher(){const d=await api('/api/management/sessions');teacherSessions=Array.isArray(d.sessions)?d.sessions:[];renderTeacher()}","async function loadTeacher(){const pair=await Promise.all([api('/api/management/sessions'),api('/api/management/student-codes')]);teacherSessions=Array.isArray(pair[0].sessions)?pair[0].sessions:[];teacherRecords=Array.isArray(pair[1].students)?pair[1].students:[];renderTeacher()}")
pattern=r"function teacherGroups\(\)\{.*?\}\nfunction renderTeacherLine"
replacement="""function filteredTeacherSessions(){const c=$('teacherClass').value;return c==='all'?teacherSessions:teacherSessions.filter(s=>String(s.classId||'')===c)}
function teacherGroups(){const m={};filteredTeacherSessions().forEach(s=>{const key=String(s.studentId||'')||'UNKNOWN';(m[key]||(m[key]=[])).push(s)});return m}
function renderTeacher(){const rows=filteredTeacherSessions(),g=teacherGroups(),ids=Object.keys(g);$('teacherStudents').textContent=ids.length+'人';$('teacherSessions').textContent=rows.length+'回';$('teacherAvgSessions').textContent=(ids.length?(rows.length/ids.length).toFixed(1):'0')+'回';$('studentRows').innerHTML=ids.map(id=>{const a=g[id],last=a.slice().sort((x,y)=>String(y.endedAt).localeCompare(String(x.endedAt)))[0]||{},display=last.teacherStudentId||String(id).replace(/[^A-Za-z0-9]/g,'').slice(0,4).toUpperCase();return '<tr><td><button class=\"link student-link\" data-id=\"'+esc(id)+'\">'+esc(display)+'</button></td><td>'+a.length+'回</td><td>'+mins(a.reduce((t,s)=>t+(Number(s.actualDurationSeconds)||0),0))+'</td><td>'+avg(a,'totalTurns').toFixed(1)+'回</td><td>'+avg(a,'totalChildWords').toFixed(0)+'語</td><td>'+esc(String(last.endedAt||'').slice(0,10))+'</td><td><span class=\"status\">利用中</span></td></tr>'}).join('');document.querySelectorAll('.student-link').forEach(el=>el.addEventListener('click',()=>openStudent(el.dataset.id||'')));$('codeRows').innerHTML=teacherRecords.map(r=>'<tr><td>'+esc(r.teacherStudentId||'----')+'</td><td>'+esc(r.classId||'未設定')+'</td><td><span class=\"status\">'+(r.active?'利用中':'利用停止')+'</span></td><td>'+esc(String(r.updatedAt||'').slice(0,10))+'</td><td><button class=\"secondary reissue-btn\" data-id=\"'+esc(r.studentId)+'\">再発行</button> <button class=\"'+(r.active?'danger':'secondary')+' active-btn\" data-id=\"'+esc(r.studentId)+'\" data-active=\"'+String(r.active)+'\">'+(r.active?'利用停止':'再開')+'</button></td></tr>').join('');document.querySelectorAll('.reissue-btn').forEach(el=>el.addEventListener('click',()=>reissueCode(el.dataset.id||'')));document.querySelectorAll('.active-btn').forEach(el=>el.addEventListener('click',()=>toggleActive(el.dataset.id||'',el.dataset.active==='true')));renderTeacherLine(rows)}
function renderTeacherLine"""
s,n=re.subn(pattern,replacement,s,flags=re.S)
assert n==1,n
s=s.replace("function openStudent(id){selectedStudent=id;const a=teacherGroups()[id]||[];$('studentSummaryTitle').textContent=id+'の学習状況';", "function openStudent(id){selectedStudent=id;const a=teacherGroups()[id]||[],display=a[0]?.teacherStudentId||String(id).replace(/[^A-Za-z0-9]/g,'').slice(0,4).toUpperCase();$('studentSummaryTitle').textContent=display+'の学習状況';")
old_issue="async function issueCode(){const code=$('newCode').value.trim().toUpperCase();if(!/^[A-Z0-9]{4}$/.test(code)){$('codeMessage').className='error';$('codeMessage').textContent='英数字4文字で入力してください';return}try{const d=await api('/api/management/student-codes',{method:'POST',body:JSON.stringify({learningCode:code,classId:$('newClass').value})});$('codeMessage').className='ok';$('codeMessage').textContent='発行しました: '+code+' / 児童ID '+String(d.studentId||'').slice(0,8)}catch(e){$('codeMessage').className='error';$('codeMessage').textContent='発行できません: '+e.message}}"
new_issue="""async function issueCode(){const code=$('newCode').value.trim().toUpperCase();if(!/^[A-Z0-9]{4}$/.test(code)){$('codeMessage').className='error';$('codeMessage').textContent='英数字4文字で入力してください';return}try{const d=await api('/api/management/student-codes',{method:'POST',body:JSON.stringify({action:'create',learningCode:code,classId:$('newClass').value})});$('codeMessage').className='ok';$('codeMessage').textContent='発行しました: '+code+' / 児童ID '+String(d.studentId||'').replace(/[^A-Za-z0-9]/g,'').slice(0,4).toUpperCase();$('newCode').value='';await loadTeacher()}catch(e){$('codeMessage').className='error';$('codeMessage').textContent='発行できません: '+e.message}}
async function reissueCode(studentId){const code=String(prompt('新しい4文字コードを入力してください')||'').trim().toUpperCase();if(!code)return;if(!/^[A-Z0-9]{4}$/.test(code)){alert('英数字4文字で入力してください');return}try{await api('/api/management/student-codes',{method:'POST',body:JSON.stringify({action:'reissue',studentId,learningCode:code})});alert('新しいコードを発行しました: '+code);await loadTeacher()}catch(e){alert('再発行できません: '+e.message)}}
async function toggleActive(studentId,current){const label=current?'利用停止':'再開';if(!confirm(label+'しますか？'))return;try{await api('/api/management/student-codes',{method:'POST',body:JSON.stringify({action:'set-active',studentId,active:!current})});await loadTeacher()}catch(e){alert(label+'できません: '+e.message)}}"""
assert old_issue in s
s=s.replace(old_issue,new_issue)
s=s.replace("function renderResearch(){const g={};researchRows.forEach", "function renderResearch(){const selectedClass=$('researchClass')?.value||'all',source=selectedClass==='all'?researchRows:researchRows.filter(s=>String(s.class_id||'')===selectedClass),g={};source.forEach")
s=s.replace("$('researchSessions').textContent=researchRows.length+'件';$('researchMissing').textContent=researchRows.filter", "$('researchSessions').textContent=source.length+'件';$('researchMissing').textContent=source.filter")
s=s.replace("const dates=researchRows.map", "const dates=source.map")
s=s.replace("const vals=researchRows.slice(-8)", "const vals=source.slice(-8)")
s=s.replace("$('loginBtn').addEventListener", "$('teacherClass').addEventListener('change',renderTeacher);$('researchClass').addEventListener('change',renderResearch);$('loginBtn').addEventListener")
p.write_text(s)
print('stage2 management patch applied')
