from pathlib import Path

p = Path('server.ts')
s = p.read_text()
old_import = "import { createStudentCode, getAllSessionsForManagement, getStudentHistory, anonymizeSessionForResearch, persistenceConfigured, resolveStudentByCode, saveCanonicalSession } from './src/server/persistence';"
new_import = "import { createStudentCode, getAllSessionsForManagement, getTeacherSessionsForManagement, getStudentHistory, getStudentRecordsForManagement, reissueStudentCode, setStudentActive, anonymizeSessionForResearch, persistenceConfigured, resolveStudentByCode, saveCanonicalSession } from './src/server/persistence';"
assert old_import in s
s = s.replace(old_import, new_import)

old_save = "const saved=await saveCanonicalSession({sessionId:validated.value.sessionId,studentId:student.studentId,researchId:student.researchId,aiStudentId:validated.value.aiStudentId,topic:validated.value.topic,targetDurationMinutes:validated.value.targetDurationMinutes,startedAt:validated.value.startedAt,endedAt:validated.value.endedAt,history:validated.value.history,encounteredVocab:validated.value.encounteredVocab||[],reflection:validated.value.reflection});"
new_save = "const saved=await saveCanonicalSession({sessionId:validated.value.sessionId,studentId:student.studentId,researchId:student.researchId,classId:student.classId,aiStudentId:validated.value.aiStudentId,topic:validated.value.topic,targetDurationMinutes:validated.value.targetDurationMinutes,startedAt:validated.value.startedAt,endedAt:validated.value.endedAt,history:validated.value.history,encounteredVocab:validated.value.encounteredVocab||[],reflection:validated.value.reflection});"
assert old_save in s
s = s.replace(old_save, new_save)

start = s.index("app.post('/api/management/student-codes'")
end = s.index("function csvCell", start)
replacement = """app.get('/api/management/student-codes', requireManagementRole(['teacher']), async (_req,res) => {\n  try { const students=await getStudentRecordsForManagement(); res.setHeader('Cache-Control','no-store'); return res.json({success:true,students}); }\n  catch(error:any){console.error('Student code list failed',{message:error?.message});return res.status(503).json({success:false,error:'CODE_LIST_UNAVAILABLE'});}\n});\napp.post('/api/management/student-codes', requireManagementRole(['teacher']), async (req,res) => {\n  const action=typeof req.body?.action==='string'?req.body.action:'create';\n  try {\n    if(action==='create'){const code=normalizeLearningCode(req.body?.learningCode);if(!isValidLearningCode(req.body?.learningCode))return res.status(400).json({success:false,error:'INVALID_LEARNING_CODE'});const created=await createStudentCode(code,undefined,undefined,req.body?.classId);return res.json({success:true,studentId:created.studentId,classId:created.classId});}\n    if(action==='reissue'){const studentId=typeof req.body?.studentId==='string'?req.body.studentId:'';if(!studentId||!isValidLearningCode(req.body?.learningCode))return res.status(400).json({success:false,error:'INVALID_REISSUE_REQUEST'});const created=await reissueStudentCode(studentId,normalizeLearningCode(req.body.learningCode));return res.json({success:true,studentId:created.studentId,classId:created.classId});}\n    if(action==='set-active'){const studentId=typeof req.body?.studentId==='string'?req.body.studentId:'';if(!studentId||typeof req.body?.active!=='boolean')return res.status(400).json({success:false,error:'INVALID_ACTIVE_REQUEST'});await setStudentActive(studentId,req.body.active);return res.json({success:true});}\n    return res.status(400).json({success:false,error:'INVALID_CODE_ACTION'});\n  } catch(error:any){console.error('Student code mutation failed',{message:error?.message});const conflict=error?.message==='LEARNING_CODE_ALREADY_EXISTS';return res.status(conflict?409:503).json({success:false,error:conflict?'LEARNING_CODE_ALREADY_EXISTS':'CODE_MUTATION_UNAVAILABLE'});}\n});\napp.get('/api/management/sessions',requireManagementRole(['teacher']),async(_req,res)=>{try{const sessions=await getTeacherSessionsForManagement();res.setHeader('Cache-Control','no-store');return res.json({success:true,sessions});}catch(error:any){console.error('Management sessions failed',{message:error?.message});return res.status(503).json({success:false,error:'MANAGEMENT_DATA_UNAVAILABLE'});}});\n"""
s = s[:start] + replacement + s[end:]
p.write_text(s)
print('stage2 server patch applied')
