import vm from 'node:vm';
import assert from 'node:assert/strict';
import { managementPageHtml } from '../src/server/managementPage';
import { readFile } from 'node:fs/promises';

const html = managementPageHtml();
const scriptMatch = html.match(/<script>([\s\S]*?)<\/script>/);
if (!scriptMatch) throw new Error('Management page script not found');
new vm.Script(scriptMatch[1], { filename: 'management-page-inline.js' });
if (/onclick=/.test(html)) throw new Error('Inline onclick handlers are not allowed');
for (const marker of ['teacherDashboard','studentList','studentSummary','sessionDetail','codeManagement','researchDashboard','researchList','researchSummary','researchSession','researchQuality']) assert.ok(html.includes(`id="${marker}"`), `Management screen missing: ${marker}`);
for (const marker of ['teacherClass','teacherStart','teacherEnd','teacherMetric','teacherWeekly','teacherMonthly','teacherChart','listClass','listStart','listEnd','studentSearch','showUnused','summaryStart','summaryEnd','sumDurationChart','sumWordsChart','newCode','newClass','reissueModal','reissueConfirm','researchStart','researchEnd','researchDashboardClass','researchMetric','researchWeekly','researchMonthly','researchChart','researchClass','researchGrade','researchCompleteOnly','researchSearch','r4TurnChart','r4WordChart','r4ReflectionChart','r5Head','r5Reflection','r6Start','r6End','r6Class','r6Research','qNormal','qMissing','qDuplicate','qReview']) assert.ok(html.includes(`id="${marker}"`), `Functional UI control missing: ${marker}`);
assert.ok(html.includes('/api/management/research.csv'));
assert.ok(html.includes('/api/management/student-codes'));
assert.ok(html.includes('/api/management/sessions'));
assert.ok(html.includes("action:'reissue'"));
assert.ok(html.includes("action:'set-active'"));
assert.ok(html.includes('research-open'));
assert.ok(html.includes('r5-open'));
assert.ok(html.includes('downloadRows'));
assert.ok(html.includes('renderQuality'));
const loadResearchMatch = scriptMatch[1].match(/async function loadResearch\(\)\{([\s\S]*?)\}\nfunction setRoleUi/);
assert.ok(loadResearchMatch, 'loadResearch function not found');
assert.ok(loadResearchMatch![1].includes('/api/management/research.csv'));
assert.ok(!loadResearchMatch![1].includes('/api/management/sessions'), 'Researcher UI must not call raw teacher sessions endpoint');
const authSource = await readFile('src/server/auth.ts', 'utf8');
assert.ok(authSource.includes("path === '/api/management/research.csv'"));
assert.ok(authSource.includes('RESEARCHER_ANONYMIZED_DATA_ONLY'));
const serverSource = await readFile('server.ts', 'utf8');
assert.ok(serverSource.includes("requireManagementRole(['teacher'])"));
assert.ok(serverSource.includes('getTeacherSessionsForManagement'));
assert.ok(serverSource.includes("requireManagementRole(['researcher'])"));
assert.ok(serverSource.includes('isPredominantlyJapanese'), 'Japanese feedback guard missing');
assert.ok(serverSource.includes('studentMessageは必ず日本語で書いてください'), 'Japanese feedback prompt requirement missing');
const reflectionSource = await readFile('src/components/ReflectionScreen.tsx', 'utf8');
for (const marker of ['自分の考えを伝える','相手の話を聞いて分かる','新しい言葉や文化に気づいた','対話時間 (TIME)','ターン数 (TURNS)','発話語数 (WORDS)','出会った語彙 (VOCAB)']) assert.ok(reflectionSource.includes(marker), `Reflection UI marker missing: ${marker}`);
assert.ok(!reflectionSource.includes('もう一度練習する'), 'Retry button must not be on reflection screen');
assert.ok(!reflectionSource.includes('わたしの学習履歴'), 'History button must not be on reflection screen');
const feedbackSource = await readFile('src/components/FeedbackScreen.tsx', 'utf8');
assert.ok(!feedbackSource.includes('handleCopyReport'), 'Feedback report copy action must be removed');
assert.ok(!feedbackSource.includes('window.print()'), 'Feedback report print action must be removed');
for (const marker of ['からのメッセージ','よくできたところ (Good Points)','今回学んだ単語 (Vocab Collection)','次へのステップアップ (Next Step Advice)','重要キーフレーズ (Key Expressions)','対話の文字起こしと日本語訳','日本語訳','もう一度練習する']) assert.ok(feedbackSource.includes(marker), `Feedback UI marker missing: ${marker}`);
assert.ok(!feedbackSource.includes('Metrics Row'), 'Feedback report must not render duplicated metric cards');
const appSource = await readFile('src/App.tsx', 'utf8');
assert.ok(!appSource.includes('setTimeout(executeTransition,4500)'), 'Farewell must not auto-advance before audio finishes');
assert.ok(appSource.includes("setIsSavingReflection(false);\n    setPhase('feedback');"), 'Reflection must advance to AI feedback report');
assert.ok(appSource.includes("onBack={()=>setPhase('feedback')}"), 'History must return to AI feedback report');
assert.ok(!appSource.includes('onOpenHistory={learningDataEnabled && learningCode ? handleOpenHistory : undefined} onRestart={handleRestart}/>}'), 'Reflection must not receive retry action');
assert.ok(!appSource.includes('saveMessage={reflectionSaveMessage} onOpenHistory='), 'Reflection must not receive history action');

assert.ok(!html.includes('id="teacherClassPicks"'), 'T2 redundant display-class selector must be removed');
assert.ok(!html.includes('id="researchClassPicks"'), 'R2 must use a single class dropdown');
for (const cls of ['5-1','5-2','5-3','6-1','6-2','6-3','テスト','予備']) assert.ok(html.includes(cls), `Class option missing: ${cls}`);
assert.ok(html.includes('fillResearchScopeSelect'), 'R2 scoped class selector missing');
assert.ok(html.includes('総対話時間'));
assert.ok(html.includes("setSummaryQuick('all')"));
assert.ok(html.includes("actualDurationSeconds"));
for (const marker of ['teacherTotalDuration','teacherAvgDuration','teacherAvgTurns','teacherAvgWords','teacherClassSummary','teacherUsageSummary','researchTotalDuration','researchAvgTurns','researchAvgWords','researchClassSummary','researchUsageSummary','sumAvgDuration','sumTotalWords','r4TotalDuration','r4Themes']) assert.ok(html.includes(`id="${marker}"`), `Information-density metric missing: ${marker}`);
for (const marker of ['grade5','grade6','canonClass','classMatches','scopeClasses','fillResearchScopeSelect','topicText','UNASSIGNED_CLASS','rowClass','学級未設定']) assert.ok(html.includes(marker), `Linked dashboard logic missing: ${marker}`);
assert.ok(html.includes('累積対話時間（分）'));
const historySource = await readFile('src/components/LearningHistoryScreen.tsx', 'utf8');
for (const marker of ['累計対話時間','よく話したテーマ','よく話したAI留学生','テーマ・時間・発話量','actualDurationSeconds']) assert.ok(historySource.includes(marker), `Learning history detail missing: ${marker}`);
const setupSource = await readFile('src/components/SetupScreen.tsx', 'utf8');
assert.ok(!setupSource.includes('お名前:'), 'Non-functional name field must be removed');
assert.ok(!setupSource.includes("User className"), 'Unused name icon must be removed');
assert.ok(setupSource.includes('items-stretch'), 'Setup columns must stretch to equal height');
assert.ok(setupSource.includes('flex-1 auto-rows-fr'), 'AI student grid must fill the left column height');
assert.ok(setupSource.includes('min-h-[194px]'), 'AI student cards must be tall enough to remove lower whitespace');
assert.ok(setupSource.includes('grid-cols-[76px_minmax(0,1fr)]'));
assert.ok(setupSource.includes('max-w-[170px]'));
assert.ok(setupSource.includes('mt-auto flex min-h-12 w-full'), 'Start button must anchor at the bottom of the right column');

console.log('Learner + teacher + researcher functional UI contract QA: PASS');
