import assert from 'node:assert/strict';
import fs from 'node:fs';
const page=fs.readFileSync('src/server/managementPage.ts','utf8');const server=fs.readFileSync('server.ts','utf8');const schedule=fs.readFileSync('public/study-schedule.html','utf8');
assert.ok(page.includes('研究データ管理'));assert.ok(page.includes('research.bundle.zip'));assert.ok(!page.includes('教師用管理'));assert.ok(!page.includes('学習者ID管理'));
assert.ok(page.includes('id="scheduleBtn"'));assert.ok(page.includes('href="/study-schedule.html"'));assert.ok(page.includes('Study 1 日程管理'));
assert.ok(page.includes('7 CSVを一括ZIP'));assert.equal(page.includes('6 CSVを一括ZIP'),false,'CSV bundle label must match the seven exported CSV files');
assert.ok(page.includes("research-dashboard-rendered"),'Phase analytics must reuse the successful dashboard payload');
assert.ok(page.includes("if(filterTimer){clearTimeout(filterTimer);filterTimer=0}"),'explicit loads must cancel pending debounced reloads');
assert.ok(page.includes("dashboardLoading&&dashboardLoadingQuery===query"),'same-query dashboard requests must be deduplicated');
assert.ok(page.includes('前回正常取得時の結果です'),'failed reloads must clearly label stale on-screen metrics');
assert.ok(schedule.includes('href="/management"'));assert.ok(schedule.includes('研究ダッシュボード'));
assert.ok(server.includes("requireManagementRole(['researcher'])"));assert.ok(!server.includes("requireManagementRole(['teacher'])"));assert.ok(!server.includes("'/api/management/student-codes'"));assert.ok(!server.includes("'/api/management/sessions'"));
console.log('Research-only management/navigation QA: PASS');
