import fs from 'node:fs';

const read = (path: string) => fs.readFileSync(path, 'utf8');
const fail = (message: string): never => { throw new Error('[qa:reflection] ' + message); };
const requireText = (source: string, needle: string, label: string) => { if (!source.includes(needle)) fail(label + ' missing: ' + needle); };
const forbidText = (source: string, needle: string, label: string) => { if (source.includes(needle)) fail(label + ' must not contain: ' + needle); };
const main=read('src/main.tsx'), reflection=read('src/reflection/ReflectionApp.tsx'), css=read('src/reflection/reflection.css'), routes=read('src/server/reflectionRoutes.ts'), persistence=read('src/server/reflectionPersistence.ts'), firestore=read('src/server/firestore.ts'), teacher=read('src/reflection/ReflectionTeacherApp.tsx'), teacherModel=read('src/server/reflectionTeacherModel.ts'), serverEntry=read('server-entry.ts'), app=read('src/App.tsx'), dataContract=read('src/dataContract.ts'), vite=read('vite.config.ts'), pkg=read('package.json');
requireText(main, "endsWith('/reflection')", 'pupil route'); requireText(main, "endsWith('/reflection/teacher')", 'teacher route'); requireText(main,'ReflectionTeacherApp','teacher route'); forbidText(main,'reflection-b.css','obsolete B stylesheet'); requireText(serverEntry,"this.use('/api/reflection'",'server route mount');
for (const label of ['できたこと','使ったことば','授業中に考えていたこと','困ったこと・工夫','言葉や文化について気づいたこと','次に頑張りたいこと']) requireText(reflection,label,'six-part UI');
for (const field of ['achievements','languageUsed','thinking','difficultyStrategy','languageCultureAwareness','nextGoal']) { requireText(reflection,field,'six-part state'); requireText(routes,field,'six-part API'); requireText(persistence,field,'six-part persistence'); }
requireText(reflection,'6項目 合計','six-part char count'); requireText(reflection,'前回の「次に頑張りたいこと」','next-lesson bridge'); requireText(css,'min-height:145px','large writing fields'); forbidText(reflection,'今日のめあてに向かって学ぶことができましたか？','obsolete B rating'); forbidText(reflection,'自分で考えたり、工夫したりしながら学ぶことができましたか？','obsolete B rating');
requireText(reflection,'draftKey = (token: string)','device-scoped draft'); requireText(reflection,"timeZone: 'Asia/Tokyo'",'Tokyo boundary'); requireText(reflection,'local.savedAt > serverUpdatedAt','draft freshness'); requireText(reflection,'window.clearTimeout(timerRef.current)','autosave race'); requireText(reflection,'onRecordSaved','server-state refresh'); requireText(reflection,'REFLECTION_DEVICE_REBIND_REQUIRED','rebind handling'); requireText(reflection,'もう一度読み込む','transient retry');
for (const route of ["router.post('/register'","router.post('/bootstrap'","router.post('/save'","router.post('/history'","router.post('/class'","router.post('/teacher/login'","router.post('/teacher/dashboard'","router.post('/teacher/student'","router.post('/teacher/export.csv'"]) requireText(routes,route,'route'); requireText(routes,"requireManagementRole(['teacher'])",'teacher auth'); requireText(routes,'resolveStudentByCode(registered.learningId)','live identity recheck'); requireText(routes,'REFLECTION_DEVICE_REBIND_REQUIRED','stale token guard'); requireText(routes,'TOO_MANY_FAILED_CODE_ATTEMPTS','code rate limit'); forbidText(routes,'researchId: record.researchId','pupil response');
requireText(persistence,"const DEVICE_COLLECTION = 'reflection_devices'",'reflection device collection'); requireText(persistence,"const REFLECTION_COLLECTION = 'lesson_reflections'",'reflection collection'); requireText(persistence,"input.status === 'submitted' || existing?.status === 'submitted'",'monotonic submit'); requireText(persistence,'queryCollectionByEqualities','exact peer query'); requireText(persistence,'sixPartCount > 0 ? sixPartCount','six-part canonical char count'); requireText(firestore,'compositeFilter','multi-field query');
requireText(teacher,'できたこと','teacher six fields'); requireText(teacher,'次に頑張りたいこと','teacher next goal'); requireText(teacherModel,"'achievements'",'teacher CSV six fields'); requireText(teacherModel,"'next_goal'",'teacher CSV six fields'); requireText(teacherModel,"if (/^\\s*[=+\\-@]/.test(text))",'CSV injection guard'); forbidText(teacherModel,"'research_id'",'teacher CSV internal id'); forbidText(teacherModel,"'student_id'",'teacher CSV internal id');
forbidText(app,'lesson_reflections','AI App isolation'); forbidText(app,'ReflectionApp','AI App isolation'); forbidText(dataContract,'lesson_reflections','AI data contract isolation'); forbidText(reflection,'静岡大学','standalone reflection'); forbidText(reflection,'留学生','standalone reflection'); forbidText(reflection,'Unit','standalone reflection');
requireText(vite,"process.env.VITE_DEPLOY_TARGET === 'pages'",'deployment base'); requireText(vite,"'/shizuoka-english-ai/'",'Pages base'); requireText(pkg,'VITE_DEPLOY_TARGET=pages vite build','Pages target'); requireText(pkg,'dist/reflection/teacher','teacher static route'); requireText(pkg,'"build": "vite build && npm run build:server"','Cloud Run build isolation');
console.log('[qa:reflection] PASS: six-part canonical schema + identity, autosave, privacy, teacher, route and deployment hardening verified.');
