import assert from 'node:assert/strict';
import { isValidLearningCode, parseReflectionAnswers } from '../src/dataContract';
assert.equal(isValidLearningCode('A7M4'), true);
assert.equal(isValidLearningCode('bad!'), false);
assert.equal(parseReflectionAnswers({conveyedIdeas:1,understoodPartner:2,continuedConversation:3,noticedLanguageCulture:5})?.noticedLanguageCulture,5);
const setup=(await import('node:fs/promises')).readFile('src/components/SetupScreen.tsx','utf8');
assert.ok((await setup).includes('学習コード'));
const app=(await import('node:fs/promises')).readFile('src/App.tsx','utf8');
assert.ok((await app).includes("setPhase('reflection')"));
assert.ok((await app).includes("/api/sessions"));
console.log('STAGE 3B QA PASS');
